spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_shop?serverTimezone=UTC&useSSL=false
    username: root
    password: Kindkill0718!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  jpa:
    hibernate:
      ddl-auto: none
#       ddl -auto : create -> none 기존 테이블 생성시 더이상 생성하지말라는 none 으로 수정
    properties:
      hibernate:
  #      show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace



