spring:
  datasource:
    url: ${url}
    username: root
    password: Kindkill0718!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaabbbb
  jpa:
    hibernate:
      ddl-auto: none
#       ddl -auto : create -> none 기존 테이블 생성시 더이상 생성하지말라는 none 으로 수정
    properties:
      hibernate:
  #      show_sql: true
        format_sql: true
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: ${username}  # 3
    password: ${password} # 4
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace



